# Generated by Django 4.2 on 2025-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=256, verbose_name='Почтовый адрес')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
